#!/bin/bash.sh

if ["$1" == "" && "$2" == ""], then
	echo "Script to automate the git Add, Commit and Push got GitHub repositore."
	echo "Use:"
	echo "gitacp <file> <\"comment\">"
	echo "Example:"
	echo "gitacp . \"Added all new files and some new commnets to the project.\""
else
	git add $1
	git commit -m "$2"
	git push origin master
fi

