#!/bin/bash

# Local Variables
SUCCESSFUL="Successful"
FAILURE="Failure"

# ADD
echo "Starging Add..."
git add .
if [ $? -eq 0 ]
then
	echo "Add $SUCCESSFUL"
else
	echo "Add $FAILURE"
fi

# COMMIT
echo "Starting Commit..."
git commit -m "$1"
if [ $? -eq 0 ]
then
	echo "Commit $SUCCESSFUL"
else
	echo "Commit $FAILURE"
fi

# FETCH
echo "Starting Fetch..."
git fetch origin
if [ $? -eq 0 ]
then
	echo "Fetch $SUCCESSFUL"
else
	echo "Fetch $FAILURE"
fi

# PULL
echo "Starting Pull..."
git pull origin
if [ $? -eq 0 ]
then
	echo "Pull $SUCCESSFUL"
else
	echo "Pull $FAILURE"
fi

# PUSH
echo "Starting Push..."
git push
if [ $? -eq 0 ]
then
	echo "Push $SUCCESSFUL"
else
	echo "Push $FAILURE"
fi

# END
echo "Finished!"

